[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/"
  to = "/sales.html"
  status = 200

# Thank you page consulenza
[[redirects]]
  from = "/thankyou-consulenza"
  to = "/thankyou-consulenza.html"
  status = 200
  
# Tutti i percorsi di marketing mostrano l'optin
[[redirects]]
  from = "/mads"
  to = "/optin.html"
  status = 200
[[redirects]]
  from = "/tg"
  to = "/optin.html"
  status = 200
[[redirects]]
  from = "/igs"
  to = "/optin.html"
  status = 200
[[redirects]]
  from = "/igb"
  to = "/optin.html"
  status = 200
[[redirects]]
  from = "/tt"
  to = "/optin.html"
  status = 200
[[redirects]]
  from = "/mail"
  to = "/optin.html"
  status = 200
[[redirects]]
  from = "/ytb"
  to = "/optin.html"
  status = 200
[[redirects]]
  from = "/ytd"
  to = "/optin.html"
  status = 200

# Pagina candidatura grafico
[[redirects]]
  from = "/candidatura"
  to = "/candidatura.html"
  status = 200

# Thank you page candidatura grafico
[[redirects]]
  from = "/thankyou-candidatura"
  to = "/thankyou-candidatura.html"
  status = 200

# Pagina candidatura frontman
[[redirects]]
  from = "/ft"
  to = "/ft.html"
  status = 200

# Thank you page candidatura frontman
[[redirects]]
  from = "/thankyou-ft"
  to = "/thankyou-ft.html"
  status = 200